// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qapmywbzcfrwjvoxibaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhcG15d2J6Y2Zyd2p2b3hpYmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjIwNzIsImV4cCI6MjA2Njc5ODA3Mn0.VhWyJVJWd2C6qDTrSP-Vtw1uK1o04rVmMs5B4KMnD24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
