// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swrolhjwcumynnjkugbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3cm9saGp3Y3VteW5uamt1Z2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTMwOTksImV4cCI6MjA2Njc2OTA5OX0.Q4jxXk08zQoYTFq8wF5Q_fGBW_dXAchaj21URPXdF48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);